#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_whatsapp
SERVICE_NAME="bridge_whatsapp"

check_container_initialized

liftoff

print_start "Starting Whatsapp bridge version $(grep -o "ADD: Mautrix WhatsApp .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec sudo -u matrix /usr/local/bin/mautrix-whatsapp \
                                                -c "${WHATSAPP_CONFIG_PATH}"/"${WHATSAPP_CONFIG_FILE}"