#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_hookshot

SERVICE_NAME="bridge_hookshot"

check_container_initialized

#check_service_initialized 10-matrix_bridges
#setup_bridges

if var_true "${ENABLE_FEEDS}" ; then hookshot_bridges+="feeds " ; fi
if var_true "${ENABLE_FIGMA}" ; then hookshot_bridges+="figma " ; fi
if var_true "${ENABLE_GITHUB}" ; then hookshot_bridges+="github " ; fi
if var_true "${ENABLE_GITLAB}" ; then hookshot_bridges+="gitlab " ; fi
if var_true "${ENABLE_JIRA}" ; then hookshot_bridges+="jira " ; fi
if var_true "${ENABLE_WEBHOOKS}" ; then hookshot_bridges+="webhooks " ; fi
liftoff

print_start "Starting Hookshot ($(echo ${hookshot_bridges} | sed "s| $||g")) bridge version $(grep -o "ADD: Matrix Hookshot .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
cd /opt/hookshot
sudo -u matrix exec node bin/matrix-hookshot/App/BridgeApp.js \
                                                                /data/config.yml \
                                                                /data/registration.yml

