#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_signal

SERVICE_NAME="bridge_signal"

check_container_initialized

liftoff

print_start "Starting Signal bridge version $(grep -o "ADD: Mautrix Signal .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec sudo -u matrix /usr/local/bin/mautrix-signal \
                                        -c "${SIGNAL_CONFIG_PATH%/}"/"${SIGNAL_CONFIG_FILE}"