#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_instagram

SERVICE_NAME="bridge_instagram"

check_container_initialized

#check_service_initialized 10-matrix_bridges
liftoff

print_start "Starting Instagram bridge version $(grep -o "ADD: Mautrix Meta .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
sudo -u matrix /usr/local/bin/mautrix-meta \
                            -c "${INSTAGRAM_CONFIG_PATH}"/"${INSTRAGRAM_CONFIG_FILE}"
