#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_slack

SERVICE_NAME="bridge_slack"

check_container_initialized

#check_service_initialized 10-matrix_bridges

liftoff

print_start "Starting Slack bridge version $(grep -o "ADD: Mautrix Slack .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec sudo -u matrix /usr/local/bin/mautrix-slack \
                                            -c "${SLACK_CONFIG_PATH%/}"/"${SLACK_CONFIG_FILE}"
