#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
check_container_initialized

source /container/functions/00-container
SERVICE_NAME="bridge_slack"
source /container/defaults/matrix_bridges
source /container/defaults/bridge_slack

check_container_initialized
#check_service_initialized 10-matrix_bridges
liftoff

print_start "Starting Slack bridge version ${SLACK_VERSION}"
sudo -u matrix exec /usr/bin/mautrix-slack \
                                            -c "${SLACK_CONFIG_PATH}"/"${SLACK_CONFIG_FILE}"
