#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_facebook

SERVICE_NAME="bridge_facebook"

check_container_initialized

#check_service_initialized 10-matrix_bridges-init

liftoff
cd "${LOG_PATH}"
print_start "Starting Facebook bridge version $(grep -o "ADD: Mautrix Meta .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec sudo -u matrix /usr/local/bin/mautrix-meta \
                                    -c "${FACEBOOK_CONFIG_PATH}"/"${FACEBOOK_CONFIG_FILE}"
