#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_discord

SERVICE_NAME="bridge_discord"

check_container_initialized

#check_service_initialized 10-matrix_bridges
liftoff

print_start "Starting Discord bridge version $(grep -o "ADD: Mautrix Discord .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
sudo -u matrix exec /usr/local/bin/mautrix-discord \
                                                -c "${DISCORD_CONFIG_PATH}"/"${DISCORD_CONFIG_FILE}"