#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_discord

SERVICE_NAME="bridge_discord"

check_container_initialized

#check_service_initialized 10-matrix_bridges
liftoff

print_start "Starting Discord bridge version ${DISCORD_VERSION}"
exec udo -u matrix exec /usr/bin/mautrix-discord \
                                                -c "${WHATSAPP_CONFIG_PATH}"/"${WHATSAPP_CONFIG_FILE}"