#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/matrix_bridges
source /container/defaults/bridge_telegram

SERVICE_NAME="bridge_telegram"

check_container_initialized
#check_service_initialized 10-matrix_bridges

liftoff

cd "${LOG_PATH}"
print_start "Starting Telegram bridge version $(grep -o "ADD: Mautrix Telegram .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec sudo -u matrix python3 \
                            -m mautrix_telegram \
                            -c "${TELEGRAM_CONFIG_PATH}"/"${TELEGRAM_CONFIG_FILE}"
